// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Fri, 10 Apr 2015 06:37:49 GMT

using System.Reflection;

[assembly: AssemblyVersion("2.0.18310.0")]
[assembly: AssemblyFileVersion("2.0.18310.637")]
