// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Tue, 26 Jan 2016 10:57:45 GMT

using System.Reflection;

[assembly: AssemblyVersion("2.2.19226.0")]
[assembly: AssemblyFileVersion("2.2.19226.1057")]
