// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Thu, 09 Apr 2015 15:45:19 GMT

using System.Reflection;

[assembly: AssemblyVersion("1.0.18309.0")]
[assembly: AssemblyFileVersion("1.0.18309.1545")]
